# site configuration
site_name: pangadfs-pydfs
site_url: https://sansbacon.github.io/pangadfs-pydfs/
site_description: plugin for pangadfs interop with pydfs-lineup-optimizer
site_author: Eric Truett
repo_url: https://github.com/sansbacon/pangadfs-pydfs

theme:
  name: material

plugins:
  - search
  - mkdocstrings

markdown_extensions:
  - toc
  - admonition
  - def_list
  - pymdownx.tabbed
  - pymdownx.superfences

nav:
    - pangadfs-pydfs: index.md
    - Building apps with pangadfs-pydfs: about.md
    - Code Reference:
        - pydfs: pydfs-reference.md
